AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # 1. ల్యాంబ్డా ఫంక్షన్ డెఫినిషన్
  MyLocalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 30
      CodeUri: mylambda/
      
      # పర్మిషన్లు ఇక్కడ ఉండాలి (Function కింద)
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - "bedrock:InvokeModel"
                - "bedrock:InvokeModelWithResponseStream"
              Resource: "*"
            - Effect: Allow
              Action:
                - "dynamodb:PutItem"
                - "dynamodb:GetItem"
                - "dynamodb:Query"
                - "dynamodb:UpdateItem"
              Resource: !GetAtt MyChatHistoryTable.Arn
            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "arn:aws:logs:*:*:*"

      # ఈవెంట్స్ (API Gateway) కూడా ఇక్కడే ఉండాలి
      Events:
        MyApiEvent:
          Type: Api
          Properties:
            Path: /ask
            Method: post

  
  MyChatHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyChatHistoryTable
      AttributeDefinitions:
        - AttributeName: userid
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true