name: Enterprise Lambda Deploy
on:
  push:
    branches: [ main ] 

permissions:
  id-token: write   
  contents: read    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590184123279:role/GitHubActionDeploymentRole
          aws-region: us-east-1

      - name: Deploy with SAM
        run: |
          # 1. Build the Lambda and its dependencies
          sam build 
          
          # 2. Deploy to AWS
          sam deploy \
            --stack-name enterprise-lambda-stack \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset